version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_node
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lembretes_db
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./db_data
      o: bind
